# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

datas = [
    ('index.html', '.'),
    ('comment_reply.html', '.'),
    ('logs.html', '.'),
    ('docs.html', '.'),
    ('douyin_reply.html', '.'),
    ('xiaohongshu_reply.html', '.'),
    ('xianyu_reply.html', '.'),
    ('ai_reply.html', '.'),
    ('dashboard.html', '.'),
    ('style.css', '.'),
    ('comment_style.css', '.'),
    ('logs_style.css', '.'),
    ('docs_style.css', '.'),
    ('douyin_style.css', '.'),
    ('douyin_theme.css', '.'),
    ('xiaohongshu_theme.css', '.'),
    ('weibo_theme.css', '.'),
    ('xianyu_theme.css', '.'),
    ('ai_reply.css', '.'),
    ('dashboard.css', '.'),
    ('platform_tabs.css', '.'),
    ('script.js', '.'),
    ('comment_script.js', '.'),
    ('logs_script.js', '.'),
    ('docs_script.js', '.'),
    ('douyin_script.js', '.'),
    ('xiaohongshu_script.js', '.'),
    ('ai_mode.js', '.'),
    ('ai_reply.js', '.'),
    ('dashboard.js', '.'),
    ('platform_tabs.js', '.'),
    ('platform_import.js', '.'),
    ('platform_log_view.js', '.'),
    ('tik-tok.png', '.'),
    ('xiaohongshu-seeklogo.png', '.'),
    ('sina-weibo-seeklogo.png', '.'),
    ('bilibili.png', '.'),
    ('openai.png', '.'),
    ('xianyu.jpg', '.'),
    ('icons8-人-50.png', '.'),
    ('icons8-知识库-50.png', '.'),
    ('icons8-设置-50.png', '.'),
    ('docker/defaults/config.json', '.'),
    ('docker/defaults/keywords.json', '.'),
    ('docker/defaults/comment_config.json', '.'),
    ('docker/defaults/comment_keywords.json', '.'),
    ('docker/defaults/comment_rules.json', '.'),
    ('docker/defaults/user_reply_stats.json', '.'),
    ('docker/defaults/douyin_config.json', '.'),
    ('docker/defaults/douyin_keywords.json', '.'),
    ('docker/defaults/xiaohongshu_config.json', '.'),
    ('docker/defaults/xiaohongshu_keywords.json', '.'),
    ('docker/defaults/weibo_config.json', '.'),
    ('docker/defaults/weibo_keywords.json', '.'),
    ('docker/defaults/xianyu_config.json', '.'),
    ('docker/defaults/xianyu_keywords.json', '.'),
]

hiddenimports = [
    'flask',
    'werkzeug',
    'jinja2',
    'click',
    'itsdangerous',
    'markupsafe',
    'requests',
    'urllib3',
    'certifi',
    'charset_normalizer',
    'idna',
    'bili_wbi',
    'ai_handoff_store',
    'ai_conversation_store',
    'ai_reply_service',
    'dashboard_metrics',
    'comment_monitor_helpers',
    'comment_reply_system',
    'comment_playwright',
    'douyin_reply_system',
    'douyin_playwright',
    'xiaohongshu_reply_system',
    'xiaohongshu_playwright',
    'weibo_reply_system',
    'weibo_playwright',
    'xianyu_reply_system',
    'xianyu_playwright',
    'playwright.sync_api',
]

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='BiliGo',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
